# JARVIS AI Configuration File
app:
  name: "JARVIS AI"
  version: "1.0.0"
  debug: true
  log_level: "DEBUG"

# NLP Engine Configuration
nlp:
  model_name: "microsoft/DialoGPT-medium"
  max_length: 512
  temperature: 0.7
  confidence_threshold: 0.6
  use_local_model: false
  fallback_responses:
    - "I'm not sure about that. Could you rephrase your question?"
    - "Let me think about that differently. Can you provide more context?"
    - "I need more information to give you a proper answer."

# Memory Management Configuration
memory:
  db_type: "chromadb"  # Options: chromadb, neo4j
  chroma_path: "data/chroma_db"
  embedding_model: "all-MiniLM-L6-v2"
  max_conversation_history: 100
  max_knowledge_items: 1000

# API Integrations Configuration
api_integrations:
  openai:
    api_key: "your-openai-api-key-here"
    model: "gpt-3.5-turbo"
    max_tokens: 1000
  huggingface:
    api_key: "your-huggingface-api-key-here"
    model: "microsoft/DialoGPT-medium"
  news_api:
    api_key: "your-news-api-key-here"
    sources: ["security-news", "tech-news"]

# Vision Engine Configuration
vision:
  enabled: true
  models:
    object_detection: "yolov8n"
    ocr: "tesseract"
    face_recognition: "face_recognition"
  cache_path: "data/vision_cache"
  max_cache_size_mb: 500

# Ethical AI Configuration
ethical_ai:
  enabled: true
  strict_mode: true
  violation_log_path: "data/ethical_violations"
  guidelines:
    - "No harmful content"
    - "Respect privacy"
    - "Be truthful and accurate"
    - "Avoid bias and discrimination"

# Reasoning Engine Configuration
reasoning:
  enabled: true
  max_reasoning_steps: 10
  confidence_threshold: 0.7
  use_chain_of_thought: true

# Self-Correction Configuration
self_correction:
  enabled: true
  confidence_threshold: 0.6
  inconsistency_threshold: 0.3
  log_corrections: true
  self_correction_log_path: "data/self_correction_log/corrections.jsonl"

# Learning Configuration
learning:
  enabled: true
  feedback_log_path: "data/feedback_logs"
  scraping_enabled: false
  scraping_sources: []
  max_scraped_items_per_run: 50
  scraping_log_path: "data/scraping_logs/scraping.jsonl"
  realtime_feeds:
    enabled: false
    interval_seconds: 300
    sources: []

# Human-AI Teaming Configuration
human_ai_teaming:
  enabled: true
  adaptive_communication: true
  clarification_threshold: 0.5
  max_clarification_attempts: 3

# Voice Interface Configuration
voice:
  enabled: true
  stt_engine: "google"  # Options: google, whisper
  tts_engine: "gtts"    # Options: gtts, espnet
  language: "en"
  voice_commands:
    wake_word: "jarvis"
    stop_word: "stop"

# Collaboration Hub Configuration
collaboration:
  enabled: true
  max_sessions: 10
  session_timeout_minutes: 30

# Deployment Configuration
deployment:
  environment: "development"  # Options: development, staging, production
  docker:
    enabled: false
    image_name: "jarvis-ai"
    tag: "latest"
  kubernetes:
    enabled: false
    namespace: "jarvis-ai"

# Real-time Feeds Configuration
realtime_feeds:
  enabled: false
  interval_seconds: 300
  sources: []
